UniversityRegistrar/Models/Course.cs
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
    public class Course
    {
        public Course() 
        {
            this.JoinEntities = new HashSet<CourseStudent>();
        }
        public int CourseId { get; set; }
        public string Name { get; set; }
        public string CourseNumber { get; set; } 
        public virtual ICollection<CourseStudent> JoinEntities { get; set; }
    }
}

UniversityRegistrar/Models/CourseStudent.cs
namespace UniversityRegistrar.Models
{
  public class CourseStudent
  {
    public int CourseStudentId { get; set; }
    public int StudentId { get; set; }
    public int CourseId { get; set; }
    public virtual Student Student { get; set; }
    public virtual Course Course { get; set; }
  }
}

UniversityRegistrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {
    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfiguration configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();
      
      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Student.cs
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
    public class Student
    {
        public Student() 
        {
            this.JoinEntities = new HashSet<CourseStudent>();
        }

        public int StudentId { get; set; }
        public string Name { get; set; }
        public DateTime DateOfEnrollment { get; set; }
        public virtual ICollection<CourseStudent> JoinEntities { get; set; }
    }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
  {
    public virtual DbSet<Course> Courses { get; set; }
    public DbSet<Student> Students { get; set; }
    public DbSet<CourseStudent> CourseStudents { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

UniversityRegistrar/Controllers/CoursesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers 
  {
    public class CoursesController : Controller
    {
      private readonly UniversityRegistrarContext _db;
      public CoursesController(UniversityRegistrarContext db)
      {
        _db = db;
      }

      public ActionResult Index()
      {
        List<Course> model = _db.Courses.ToList();
        return View(model);
      }

      public ActionResult Create()
      {
        return View();
      }

      [HttpPost]
      public ActionResult Create(Course course)
      {
        if (String.IsNullOrWhiteSpace(course.Name) == false && String.IsNullOrWhiteSpace(course.CourseNumber) == false)
        {
          _db.Courses.Add(course);
          _db.SaveChanges();
        }
        return RedirectToAction("Index");
      }
      
      public ActionResult Details(int id)
      {
        Course thisCourse = _db.Courses
          .Include(course => course.JoinEntities)
          .ThenInclude(join => join.Student)
          .FirstOrDefault(course => course.CourseId == id);
        return View(thisCourse);
      }

      public ActionResult AddStudent(int id)
      {
        Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
        ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "Name");
        return View(thisCourse);
      }

      [HttpPost]
      public ActionResult AddStudent(Course course, int studentId)
      {
        if (studentId != 0)
        {
          _db.CourseStudents.Add(new CourseStudent() { StudentId=studentId, CourseId=course.CourseId });
        }
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = course.CourseId });
      }

      public ActionResult Delete(int id)
      {
        Course thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
        return View(thisCourse);
      }

      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
        Course thisCourse = _db.Courses.FirstOrDefault(course => id == course.CourseId);
        if (id != 0)
        {
          _db.Courses.Remove(thisCourse);
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

      [HttpPost]
      public ActionResult DropStudent(int joinId, int courseId)
      {
        CourseStudent joinEntry = _db.CourseStudents.FirstOrDefault(entry => entry.CourseStudentId == joinId);
        _db.CourseStudents.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = courseId });
      }
    }
  }

UniversityRegistrar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace UniversityRegistrar.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

UniversityRegistrar/Controllers/StudentsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers 
  {
    public class StudentsController : Controller
    {
      private readonly UniversityRegistrarContext _db;
      public StudentsController(UniversityRegistrarContext db)
      {
        _db = db;
      }

      public ActionResult Index()
      {
        List<Student> model = _db.Students.ToList();
        return View(model);
      }

      public ActionResult Create()
      {
        return View();
      }

      [HttpPost]
      public ActionResult Create(Student student)
      {
        _db.Students.Add(student);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
      public ActionResult Details(int id)
      {
        Student thisStudent = _db.Students
          .Include(student => student.JoinEntities)
          .ThenInclude(join => join.Course)
          .FirstOrDefault(student => student.StudentId == id);
        return View(thisStudent);
      }

      public ActionResult AddCourse(int id)
      {
        Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
        ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
        return View(thisStudent);
      }

      [HttpPost]
      public ActionResult AddCourse(Student student, int courseId)
      {
        if (courseId != 0)
        {
          _db.CourseStudents.Add(new CourseStudent() { StudentId=student.StudentId, CourseId=courseId });
        }
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = student.StudentId });
      }


      public ActionResult Delete(int id)
      {
        Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
        return View(thisStudent);
      }

      [HttpPost, ActionName("Delete")]
      public ActionResult DeleteConfirmed(int id)
      {
        Student thisStudent = _db.Students.FirstOrDefault(student => id == student.StudentId);
        if (id != 0)
        {
          _db.Students.Remove(thisStudent);
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

      [HttpPost]
      public ActionResult DropCourse(int joinId, int studentId)
      {
        CourseStudent joinEntry = _db.CourseStudents.FirstOrDefault(entry => entry.CourseStudentId == joinId);
        _db.CourseStudents.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Details", new {id = studentId});
      }
    }
  }

UniversityRegistrar/Views/Courses/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course;

<h1>Enroll student in course @Model.CourseNumber: @Model.Name</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)
  @Html.DropDownList("StudentId");
  <input type="submit" value="Enroll" />
}

<p>@Html.ActionLink("Back to courses", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course;

<h1>Add Course</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name);
  @Html.TextBoxFor(model => model.Name);

  @Html.LabelFor(model => model.CourseNumber);
  @Html.TextBoxFor(model => model.CourseNumber);

  <input type="submit" value="Add course" />
}

<p>@Html.ActionLink("Back to courses", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Course;

<h1>Deleting @Model.CourseNumber: @Model.Name</h1>

<p>Are you sure you want to delete this course?</p>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete course" />
}
<p>@Html.ActionLink("Back to course", "Details", new { id = @Model.CourseId });</p>
<p>@Html.ActionLink("Back to courses", "Index")</p>

UniversityRegistrar/Views/Courses/Details.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model UniversityRegistrar.Models.Course;

<h1>@Model.Name</h1>
<h2>@Model.CourseNumber</h2>

<h3>Students enrolled:</h3>

@if (Model.JoinEntities.Count == 0)
{
  <p>No students have enrolled in this course yet.</p>
}
<ul>
  @foreach(CourseStudent join in Model.JoinEntities)
  {
    <li>@Html.ActionLink(join.Student.Name, "Details", "Students", new { id = join.Student.StudentId})</li>
    @using (Html.BeginForm("DropStudent", "Courses"))
    {
      @Html.Hidden("courseId", join.CourseId)
      @Html.Hidden("joinId", join.CourseStudentId)
      <input type="submit" value="Drop student" />
    }
  }
</ul>

<p>@Html.ActionLink("Enroll student", "AddStudent", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Back to courses", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Course>;

<h1>Courses</h1>

@if (Model.Count == 0)
{
  <p>No courses have been added yet.</p>
}

<ul>
@foreach (Course course in Model)
{
  <li>@Html.ActionLink($"{course.CourseNumber}: {course.Name}", "Details", new { id = course.CourseId })</li>
}
</ul>

<p>@Html.ActionLink("Add course", "Create")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Home/Index.cshtml
@{
  Layout="_Layout";
}
<h1>University Registrar</h1>
<p>@Html.ActionLink("List of courses", "Index", "Courses")</p>
<p>@Html.ActionLink("List students", "Index", "Students")</p>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>University Registrar</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

UniversityRegistrar/Views/Students/AddCourse.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student;

<h1>Enroll student @Model.Name in course</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StudentId)
  @Html.DropDownList("CourseId");
  <input type="submit" value="Enroll" />
}

<p>@Html.ActionLink("Back to Students", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Students/Create.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student;

<h1>Add Student</h1>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name);
  @Html.TextBoxFor(model => model.Name);

  @Html.LabelFor(model => model.DateOfEnrollment);
  @Html.EditorFor(model => model.DateOfEnrollment, new { htmlAttributes  = new { @type = "date" }});
  <input type="submit" value="Add student" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to students", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Students/Delete.cshtml
@{
  Layout = "_Layout";
}

@model UniversityRegistrar.Models.Student;

<h1>Deleting @Model.Name</h1>

<p>Are you sure you want to delete this student?</p>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete student" />
}
<p>@Html.ActionLink("Back to student", "Details", new { id = Model.StudentId });</p>
<p>@Html.ActionLink("Back to studenets", "Index")</p>

UniversityRegistrar/Views/Students/Details.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model UniversityRegistrar.Models.Student;

<h1>@Model.Name</h1>
<h3>Enrollment date: @Model.DateOfEnrollment.ToShortDateString()</h3>

@if (Model.JoinEntities.Count == 0)
{
  <p>@Model.Name is currently enrolled in no courses.</p>
}
<ul>
@foreach (CourseStudent join in Model.JoinEntities)
{
  <li>@Html.ActionLink($"{join.Course.CourseNumber}: {join.Course.Name}", "Details", "Courses", new { id = join.Course.CourseId })</li>
  @using (Html.BeginForm("DropCourse", "Students"))
  {
    @Html.Hidden("studentId", Model.StudentId)
    @Html.Hidden("joinId", join.CourseStudentId)
    <input type="submit" value="Drop course" />
  }
}
</ul>

<p>@Html.ActionLink("Enroll in course", "AddCourse", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Delete student", "Delete", new { id = Model.StudentId })</p>
<p>@Html.ActionLink("Back to students", "Index")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>

UniversityRegistrar/Views/Students/index.cshtml
@{
  Layout = "_Layout";
}

@using UniversityRegistrar.Models;
@model List<UniversityRegistrar.Models.Student>;

<h1>Students</h1>

@if (Model.Count == 0)
{
  <p>No students have been added yet.</p>
}

<ul>
@foreach (Student student in Model)
{
  <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId }) | Enrolled @student.DateOfEnrollment.ToShortDateString()</li>
}
</ul>

<p>@Html.ActionLink("Add student", "Create")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>